#!/bin/sh

export GITHUB_JOB="Build"
export GITHUB_RUN_NUMBER="42"
export GITHUB_REF="refs/heads/master"
export GITHUB_SHA=$( git rev-parse HEAD )
export GITHUB_WORKSPACE=$( pwd )
# export GITHUB_REPOSITORY="bigdaz/dependency-extractor-client"
# export GITHUB_TOKEN="Your personal access token"

# Invoke 'build' 
./gradlew -S --no-configuration-cache -I init.gradle build